### ISSUE TITLE
Silver compatability

### ISSUE THREAD

**Issue by DechertNicholas** [DechertNicholas/ProfJamRLCraftPlus#11]
Ring of eyes needs Fire and Ice silver, not Thermal Foundation

**Comment by dharktheysus** [comment]
Glowing Ingots from Trinkets & Baubles also cannot be constructed using Thermal Foundation silver ingots - seems requires Fire & Ice Silver. My assumption is whatever correction resolves the Ring of Enchanted Eyes would also resolve this, but adding the data just in case.

**Comment by DechertNicholas** [comment]
You are correct, it will fix both
